"""create all db

Revision ID: 73bd43242e9b
Revises: 37e3e30523ff
Create Date: 2023-08-26 08:09:48.560448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bd43242e9b'
down_revision = '37e3e30523ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('people_id')
    )
    op.create_table('job_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.people_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.String(), nullable=False),
    sa.Column('math', sa.Float(), nullable=False),
    sa.Column('physics', sa.Float(), nullable=False),
    sa.Column('chemistry', sa.Float(), nullable=False),
    sa.Column('biology', sa.Float(), nullable=False),
    sa.Column('literature', sa.Float(), nullable=False),
    sa.Column('history', sa.Float(), nullable=False),
    sa.Column('geography', sa.Float(), nullable=False),
    sa.Column('philosophy', sa.Float(), nullable=False),
    sa.Column('art', sa.Float(), nullable=False),
    sa.Column('foreign_language', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.people_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('people_id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('school_performance')
    op.drop_table('job_data')
    op.drop_table('people')
    # ### end Alembic commands ###
